export const SET_MODAL_DISPLAY = 'SET_MODAL_DISPLAY';
export const SET_MODAL_MERGE_AS_SEEN = 'SET_MODAL_MERGE_AS_SEEN';
export const SET_TESTNET_FLAG = 'DASHBOARD/TESTNET/SET_IS_HIDDEN';
export const CLEAR_MODAL_DISPLAY_DATA = 'CLEAR_MODAL_DISPLAY_DATA';
