name: Build/release

on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    # runs-on: [self-hosted]

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Add msbuild to PATH
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: microsoft/setup-msbuild@v1.1

      # START windows steps
      - name: Clone keyvault-cli for windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          cd resources/win/bin
          Remove-Item 'keyvault-cli.exe'
          curl.exe -LO https://github.com/bloxapp/eth2-key-manager/releases/latest/download/keyvault-cli.exe

      - name: Build Electron app for windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          yarn install --network-timeout 1000000 && yarn dist
        env:
          GH_TOKEN: ${{ secrets.github_token }}
