name: Build/release

on: push

env:
  # AZURE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  # DOTNET_VERSION: '2.1'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build/release Electron app for windows
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn install && yarn package-win
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Setup dotnet env for sigining
        if: ${{startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get files to sign
        if: ${{startsWith(github.ref, 'refs/tags/v') }}
        run: (Get-ChildItem -File release-win | where {$_.extension -in ".exe"}).FullName >> release-win/files-to-sign.txt

      - name: AzureSignTool
        if: ${{startsWith(github.ref, 'refs/tags/v') }}
        uses: fluffy-bunny/action-azuresigntool@v0.1dev
        with:
          azure_sign_tool_credentials: ${{ secrets.AZURE_SIGN_TOOL_CREDENTIALS_MANAGED_IDENTITY }}
          azure_sign_tool_assembly: tools/AzureSignTool-DEV/netcoreapp2.1/any/AzureSignTool.dll
          files_to_sign: release-win/files-to-sign.txt

      - name: Release assets
        if: ${{startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "release-win/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
